language: cpp
depth: 1
dist: focal
os: linux
sudo: true
addons:
  apt:
    sources:
      - sourceline: “ppa:ubuntu-toolchain-r/test”
    packages:
      - gcc-11
      - g++-11
      - pip
install:
# /usr/bin/gcc points to an older compiler on Linux.
- if [ "$CXX" = "g++" ]; then export CXX="g++-11" CC="gcc-11"; fi
script:
  - pip install cmake
  - pip install conan
  - mkdir build
  - cd build
  - conan install ..
  - cmake ../
  - cmake --build . -- -j
  - ctest -j
